name: Auto Checkin

on:
  release:
    types: [ published ]
  push:
    branches: [ Login,master ]
  pull_request:
    branches: [ Login,master ]
  schedule:
    - cron: '0 8 * * *'
  watch:
    types: [ started ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Python #安装python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install requests #安装requests
        run: |
          pip install requests yagmail
      - name: Run
        env:
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
          EMAILPASSWORD: ${{ secrets.EMAILPASSWORD }}
          TARGETEMAIL: ${{ secrets.TARGETEMAIL }}
          TZ: Asia/Shanghai
        run: python3 Checkin.py
